target-version = "py311"
line-length = 100

[format]
quote-style = "double"
indent-style = "space"

[lint]
select = ["E", "F", "I", "W", "UP", "N", "SIM"]
ignore = ["E501"]

[lint.per-file-ignores]
"src/scripts/*.py" = ["N818"]
